### PR TITLE
Cli cleanup

### LINKED ISSUE #408: Crash on startup
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Describe your issue here

image
i barely got this screenshot, it crashes as soon as this message shows.

### PR DESCRIPTION
**Pull request by ScrubN**
I've been writing a new run mode but I found that having all the args in one argument class was extremely restricting. To help with this, I separated the program into verbs (like git \<verb\>).
Doing this:
- frees up some characters to be used as short forms (i.e. 'w' and 'h' were previously taken by chat render, now other modes can use them too)
- makes adding new modes insanely easy
- reduce help page length significantly
- focuses help pages to only applicable args
- allows forcing necessary args to be required (i.e. chat render didn't take --id so it couldn't be set as required previously)

NOTE: The old `-m <mode> / --mode <mode>` syntax still works because of a conversion function accompanied by a warning message notifying users about the change. Because of this, `-m` and `--mode` should not be used going forward.

In a similar fashion to separating the arguments, I separated each run mode to it's own class and file.
Doing this:
- makes developing easier since you no longer need to scroll up and down so much
- makes creating new modes or tools easy as it's obvious where they go and how they're setup
- allows `Main()` and `Program.cs` to be cleaned up immensely

I also refactored modes and tools to be better/cleaner, i.e. simplified mode option object initialization, added case for `.htm` chat downloads, clear cache no longer catches all exceptions because that was dumb

I also updated the NuGet packages in CLI and Core to current. All of the SkiaSharp libs were 2.5 years out of date and lacked support for formats such as AVIF, Newtonsoft.Json 12.0.3 had a critical security vulnerability. I tested and made sure updating did not cause any problems.

Lastly, I added a message for when no args are passed, usually indicating that a user double-clicked the executable on windows or does not know the args on Linux/Mac.
Fixes #408

### CODE REVIEW

**Comment by ScrubN** [comment]
I will notify the authors of all the wrappers I know that the syntax changed slightly when this gets merged.

File: TwitchDownloaderCLI/Modes/RenderChat.cs [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+                    "italics" => SKFontStyle.Italic,
+                    _ => throw new NotImplementedException("Invalid message font style")
+                },
+                UsernameFontStyle = inputOptions.UsernameFontStyle.ToLower() switch
+                {
+                    "normal" => SKFontStyle.Normal,
+                    "bold" => SKFontStyle.Bold,
+                    "italic" => SKFontStyle.Italic,
+                    "italics" => SKFontStyle.Italic,
+                    _ => throw new NotImplementedException("Invalid username font style")
```
Comment (goldbattle) [inline TwitchDownloaderCLI/Modes/RenderChat.cs:47]: It would be nice to include what are the valid ones in the switch defaults.

**Comment by goldbattle** [comment]
For the `TwitchDownloaderCLI/README.md` it might be nicer to just include the output of the `--help` command in a code block for each sub-mode / verb instead of trying to maintain a list.


Example from current includes the defaults too:
```
  --timestamp-format      (Default: Relative) Sets the timestamp format for .txt
                          chat logs. Valid values are Utc, Relative, and None

  --embed-emotes          Embed emotes into chat download.

  --background-color      (Default: #111111) Color of background for chat
                          render.
```

File: TwitchDownloaderCLI/Modes/Arguments/ChatDownloadArgs.cs [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+        [Option('o', "output", Required = true, HelpText = "Path to output file.")]
+        public string OutputFile { get; set; }
+
+        [Option('b', "beginning", HelpText = "Time in seconds to crop beginning.")]
+        public int CropBeginningTime { get; set; }
+
+        [Option('e', "ending", HelpText = "Time in seconds to crop ending.")]
+        public int CropEndingTime { get; set; }
+        
+        [Option('E', "embed-emotes", Default = false, HelpText = "Embed emotes into the chat download.")]
```
Comment (goldbattle) [inline TwitchDownloaderCLI/Modes/Arguments/ChatDownloadArgs.cs:22]: In my opinion, since people interfacing with the CLI will need to rework their code to update this (it is breaking e.g. not back compatible), you might as well make all the args consistent in my opinion (e.g., lowercase for all short commands).

This could be `-d` and `--download-emotes` and `Download and embed emotes into the chat download file` for example.

File: TwitchDownloaderCLI/Modes/Arguments/VideoDownloadArgs.cs [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+        [Option('b', "beginning", HelpText = "Time in seconds to crop beginning.")]
+        public int CropBeginningTime { get; set; }
+        
+        [Option('e', "ending", HelpText = "Time in seconds to crop ending.")]
+        public int CropEndingTime { get; set; }
+        
+        [Option('t', "threads", Default = 10, HelpText = "Number of download threads.")]
+        public int DownloadThreads { get; set; }
+        
+        [Option('O', "oauth", HelpText = "OAuth access token to download subscriber only VODs. DO NOT SHARE THIS WITH ANYONE.")]
```
Comment (goldbattle) [inline TwitchDownloaderCLI/Modes/Arguments/VideoDownloadArgs.cs:27]: I would just remove this shorthand IMO.

File: TwitchDownloaderCLI/Modes/Arguments/ChatDownloadArgs.cs (hunk 2 above)
Comment (goldbattle) [reply TwitchDownloaderCLI/Modes/Arguments/ChatDownloadArgs.cs:22]: I just now see the `ConvertFromOldSyntax` maybe things are ok as is, you already have kept backwards compatible.

File: TwitchDownloaderCLI/Modes/RenderChat.cs (hunk 1 above)
Comment (ScrubN) [reply TwitchDownloaderCLI/Modes/RenderChat.cs:47]: Good point

File: TwitchDownloaderCLI/Modes/Arguments/ChatDownloadArgs.cs (hunk 2 above)
Comment (ScrubN) [reply TwitchDownloaderCLI/Modes/Arguments/ChatDownloadArgs.cs:22]: Yes the rework is fully backwards compatible!

I figured since embed emotes is so common I may as well give it a short char, and `E` seemed good to me since both words start with e's

File: TwitchDownloaderCLI/Modes/Arguments/VideoDownloadArgs.cs (hunk 3 above)
Comment (ScrubN) [reply TwitchDownloaderCLI/Modes/Arguments/VideoDownloadArgs.cs:27]: fair. Oauth probably isn't very common anyways and `oauth` already is a pretty short arg name

**Comment by ScrubN** [comment]
> For the `TwitchDownloaderCLI/README.md` it might be nicer to just include the output of the `--help` command in a code block for each sub-mode / verb instead of trying to maintain a list.
> 
> Example from current includes the defaults too:
> 
> ```
>   --timestamp-format      (Default: Relative) Sets the timestamp format for .txt
>                           chat logs. Valid values are Utc, Relative, and None
> 
>   --embed-emotes          Embed emotes into chat download.
> 
>   --background-color      (Default: #111111) Color of background for chat
>                           render.
> ```

Yeah, it's a little tiring making sure both lists are accurate to each other. I'd like to know what @lay295 thinks about switching the readme's arg definitions to a copy-paste of `--help`.

**Comment by lay295** [comment]
I promise I look at your PRs tomorrow :'( this look like a big change but a good one

**Comment by ScrubN** [comment]
Sounds good. Don't forget #404 to fix the MacOS build issues

**Comment by lay295** [comment]
> Sounds good. Don't forget #404 to fix the MacOS build issues

Truly, don't know why it's an issue. I would assume this line in the publish profile would be bundling the dylib files. Don't have a Mac on hand to test but can try some stuff. I know some people in the past have successfully rendered chats on MacOS (including me) so not sure what's changed between then and now. I'll rent some cloud mac online and test stuff tomorrow.

Add rgba support on mac (https://github.com/lay295/TwitchDownloader/pull/213)

https://github.com/lay295/TwitchDownloader/blob/9d19a158032a95d1e985aa821311630d7382d76d/TwitchDownloaderCLI/Properties/PublishProfiles/MacOS.pubxml#L16

**Comment by ScrubN** [comment]
Yeah I have no clue why they don't get bundled either, especially given the fact that the Linux binary does bundle all the libraries. Looking at the build folder you can see many other dylibs that were included. For now what matters is getting a working product though, we can deal with the rogue dylibs later
