### PR TITLE
Fix VOD download trimming and quality selection

### LINKED ISSUE #935: VOD downloads "Crop Video" function is broken
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Select an Option

### Describe your issue here

since latest update of the program vod download is bugged, for example you cant normally download 3 second clip if you want to, for 7-8 second clip it only downloads 1 second, another bug is that start and end time function is not working well, it randomly cuts last 4-5 second and adds first 2-3 second when in the past it downloaded exact part it that you wanted, clearly something is broken about crop function 

### Add any related files or extra information here

_No response_

### PR DESCRIPTION
**Pull request by vaindil**
Fixes #935, see that for a more detailed discussion.

This also fixes a separate bug with stream quality selection when downloading VODs. Twitch's Usher endpoint to list stream qualities sometimes returns a `1080p60` stream quality with full framerate info, but sometimes that stream is returned as `Source` with no framerate info. Because there was no exact match for the stream name between the quality dropdown and the response when downloading, the logic would fall through to this: https://github.com/lay295/TwitchDownloader/blob/e48a04b2dd07c089cec63380c9814af17a4f36f4/TwitchDownloaderCore/Extensions/M3U8Extensions.cs#L77

However, in this case the framerate is 0 for the `Source` stream, which breaks this calculation. The other streams in the response do have framerate info when this happens, so the second-best quality would be chosen instead (720p60 in my case). This adds a manual override for these `Source` streams so they're always selected as the best quality.

### CODE REVIEW

File: TwitchDownloaderCore/Extensions/M3U8Extensions.cs [hunk 1]
```diff
@@ -118,5 +118,14 @@ public static string GetResolutionFramerateString(this M3U8.Stream stream)
 
             return $"{frameHeight}p{frameRate}";
         }
+
+        /// <summary>
+        /// Returns the best quality stream from the provided M3U8.
+        /// </summary>
+        public static M3U8.Stream BestQualityStream(this M3U8 m3u8)
+        {
+            var source = Array.Find(m3u8.Streams, x => x.MediaInfo.Name.Equals("source", StringComparison.OrdinalIgnoreCase));
```
Comment (ScrubN) [inline TwitchDownloaderCore/Extensions/M3U8Extensions.cs:127]: Sometimes "source" is called "chunked".

**Review by ScrubN — CHANGES_REQUESTED** [review]
Good thinking with the creation of `BestQualityStream`

**Comment by vaindil** [comment]
Here's a bit more detail on the second fix.

The usual response from Twitch for the playlist with video qualities in it looks like this:

image

The best-quality stream is named `1080p60`, and there's framerate info at the tail end there. When this response is returned, everything is great.

Twitch sometimes returns this response, however:

image

Note that the name is different, and there's no framerate info.

File: TwitchDownloaderCore/Extensions/M3U8Extensions.cs (hunk 1 above)
Comment (vaindil) [reply TwitchDownloaderCore/Extensions/M3U8Extensions.cs:127]: `MediaInfo.Name` can be `chunked`? I queried this a ton today while testing and never saw that occur. `StreamInfo.Video` is always `chunked`, but I never saw a value for `MediaInfo.Name` other than `1080p60` or `Source`.

Comment (ScrubN) [reply TwitchDownloaderCore/Extensions/M3U8Extensions.cs:127]: Correction: this should be `MediaInfo.Name.Contains("source", StringComparison.OrdinalIgnoreCase) || MediaInfo.GroupID.Equals("chunked", StringComparison.OrdinalIgnoreCase)`.

See https://github.com/lay295/TwitchDownloader/blob/f166581dfdecdb020b441cda5efc02c5f9a432c2/TwitchDownloaderCore.Tests/M3U8ExtensionTests.cs for an example M3U8

Comment (vaindil) [reply TwitchDownloaderCore/Extensions/M3U8Extensions.cs:127]: Oh I didn't see that test file, I'll add tests for this new extension as well.

However, I don't see any examples in there where `MediaInfo.Name` ends up as "chunked". On line 29, "chunked" is the `groupId`, and `Name` ends up as `1080p60 (source)`. I can add a test where the name is "chunked" if it needs to exist, but I don't see that currently being tested.

**Comment by ScrubN** [comment]
> Note that the name is different, and there's no framerate info.

Yeah, I ran into this myself at some point when writing M3U8Extensions. If possible, the framerate is assumed via the name when this happens:
https://github.com/lay295/TwitchDownloader/blob/e48a04b2dd07c089cec63380c9814af17a4f36f4/TwitchDownloaderCore/Tools/M3U8.cs#L619-L628

File: TwitchDownloaderCore/Extensions/M3U8Extensions.cs (hunk 1 above)
Comment (ScrubN) [reply TwitchDownloaderCore/Extensions/M3U8Extensions.cs:127]: > MediaInfo.Name

Yeah, I meant to say `MediaInfo.GroupId`, not `Name`

Comment (vaindil) [reply TwitchDownloaderCore/Extensions/M3U8Extensions.cs]: Just added in e90a07d707d3a011e16bfc4ee71db666134c4128.

File: TwitchDownloaderCore/Extensions/M3U8Extensions.cs [hunk 2]
```diff
@@ -124,7 +124,9 @@ public static string GetResolutionFramerateString(this M3U8.Stream stream)
         /// </summary>
         public static M3U8.Stream BestQualityStream(this M3U8 m3u8)
         {
-            var source = Array.Find(m3u8.Streams, x => x.MediaInfo.Name.Equals("source", StringComparison.OrdinalIgnoreCase));
+            var source = Array.Find(
+                m3u8.Streams, x => x.MediaInfo.Name.Equals("source", StringComparison.OrdinalIgnoreCase) ||
```
Comment (ScrubN) [inline TwitchDownloaderCore/Extensions/M3U8Extensions.cs:128]:
```suggestion
                m3u8.Streams, x => x.MediaInfo.Name.Contains("source", StringComparison.OrdinalIgnoreCase) ||
```

Sometimes source is in braces for live M3U8 responses.
https://github.com/lay295/TwitchDownloader/blob/e90a07d707d3a011e16bfc4ee71db666134c4128/TwitchDownloaderCore.Tests/M3U8ExtensionTests.cs#L24-L40
I know we don't support recording streams live, but maybe we will in the future or Twitch will change the VOD M3U8 response again.

Comment (vaindil) [reply TwitchDownloaderCore/Extensions/M3U8Extensions.cs]: I missed that in your original comment above, thanks!

**Comment by ScrubN** [comment]
Awesome, thank you for the fix!

**Comment by Nutri626** [comment]
is update coming soon tho, its really hard to use it properly rn

**Comment by ScrubN** [comment]
I want to release an update tomorrow at the very latest (north america), but I want to give @lay295 time to decide if he wants to implement the temporary solution for #934 first.

In the meantime, you can download the workflow build from here: https://github.com/lay295/TwitchDownloader/actions/runs/7434637911
