### PR TITLE
Misc Chat Render fixes

### LINKED ISSUE #432: Ubuntu Inter Typeface Font Fallback Fails
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

Using ubuntu 18.04 with `-h 926 -w 274 --update-rate 0.1 --framerate 60 --font-size 15` as options.
[VOD 1651230100](https://drive.google.com/file/d/1cWXMmrPn_nh7Yl-Dh96q6O-rD64WCRJ9/view?usp=sharing)

1.40.7
image

1.50.6
image

### LINKED ISSUE #433: Emojis Causing Symbol Errors
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Command Line Interface

### Describe your issue here

Seeing that the dash `-` is not being rendered correctly using 1.50.6 compared to 1.40.7
On Ubuntu 20.04 with `-h 926 -w 274 --update-rate 0.1 --framerate 60 --font-size 15` as options.
[VOD 1651230100](https://drive.google.com/file/d/1cWXMmrPn_nh7Yl-Dh96q6O-rD64WCRJ9/view?usp=sharing)

Happens 1:01 into this VOD 1.40.7 render:
image
5:46
image

But I get:
image
image

### PR DESCRIPTION
**Pull request by ScrubN**
- Fixed emoji zip not obeying custom cache and persisting after use
- Fixed emojis not being fetched on Linux
- Fixed not checking for 7TV v3 API mentioning emotes without hosted files
- Fixed Inter Embedded not being utilized by default

Fixes #433 
Fixes #432

### CODE REVIEW

**Comment by ScrubN** [comment]
Last night 7TV emotes (via v3 API) were causing an exception because of an invalid emote link so I made a quick patch to continue testing, but this morning I realized there is likely a better solution that is more logical however 7TV is no longer producing the invalid link

**Comment by ScrubN** [comment]
Right as I leave the comment the v3 API starts doing it again and my suspicion was correct

File: TwitchDownloaderCore/TwitchHelper.cs [hunk 1]
```diff
@@ -189,6 +190,10 @@ public static async Task<EmoteResponse> GetThirdPartyEmoteData(string streamerId
                     JObject emoteData = (JObject)stvEmote["data"];
                     JObject emoteHost = (JObject)emoteData["host"];
                     JArray emoteFiles = (JArray)emoteHost["files"];
+                    if (emoteFiles.Count == 0) // Sometimes there are no hosted files for the emote
+                    {
+                        continue;
+                    }
```
Comment (goldbattle) [inline TwitchDownloaderCore/TwitchHelper.cs:196]: This fixes the 404s for me.
Maybe files that are being processed have this empty?

Comment (ScrubN) [reply TwitchDownloaderCore/TwitchHelper.cs:196]: Occasionally a streamer's 7TV response contains an emote that does not have any hosted files for whatever reason. Previously my 7tv v3 implementation only used the `files` section to determine format and then builds the final URL from several other fields because the `files` section only contains a part that also overlaps with another field that is always required to build the final URL, so I took the shortcut ignoring the possibility of an empty `files` section
